import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/global/Header";
import localFont from "next/font/local";

const clashDisplay = localFont({
  src: [
    {
      path: "../public/fonts/ClashDisplay-Bold.woff",
      style: "normal",
    },
    {
      path: "../public/fonts/ClashDisplay-Semibold.woff",
      style: "normal",
    },
    {
      path: "../public/fonts/ClashDisplay-Medium.woff",
      style: "normal",
    },
  ],
  variable: "--font-clash-display",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DJ Blaqmix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${inter.variable} ${poppins.variable} ${geistMono.variable} ${clashDisplay.variable} relative antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
